{% set name = "python-mumps" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/python_mumps-{{ version }}.tar.gz
  sha256: 2cc81a86066641fa993b6636c4e9e11c7e03b43766ec7d01b40f2796067a665e
  patches:
    - 0001-disable-scotch.patch  # [target_platform == 'osx-arm64']

build:
  skip: true  # [py<311 or python_impl == 'pypy']
  number: 2

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - ninja                                  # [unix]
    - pkg-config                             # [unix]
  host:
    - python
    - cython
    - meson
    - meson-python
    - numpy
    - mumps-seq
    - setuptools-scm
    - pip
    - python-build
  run:
    - python
    - scipy >=1.11
    - mumps-seq

test:
  imports:
    - mumps
  commands:
    - pip check
    - python -c "import mumps; mumps.test()"
  requires:
    - pip
    - pytest

about:
  home: https://gitlab.kwant-project.org/kwant/python-mumps
  summary: Bindings and Python interface for the MUMPS sparse solver
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - akhmerov
