schema_version: 1

context:
  name: python-mumps
  version: 0.0.3

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/${{ name[0] }}/${{ name }}/python_mumps-${{ version }}.tar.gz
  sha256: bb10a6bb3fd1522ed5771b832f99ed0c590b2524d5ae672cbb1b7348634be550

build:
  number: 1
  skip: match(python, "<3.9") or python_impl == 'pypy'

requirements:
  build:
    - if: build_platform != target_platform
      then: python
    - if: build_platform != target_platform
      then: cross-python_${{ target_platform }}
    - if: build_platform != target_platform
      then: cython
    - if: build_platform != target_platform
      then: numpy
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - if: build_platform != target_platform
      then: python
    - if: build_platform != target_platform
      then: cross-python_${{ target_platform }}
    - if: build_platform != target_platform
      then: cython
    - if: build_platform != target_platform
      then: numpy
    - if: unix
      then: ninja
    - if: unix
      then: pkg-config
  host:
    - python
    - cython
    - meson
    - meson-python
    - numpy
    - mumps-seq
    - setuptools-scm
    - pip
    - python-build
  run:
    - python
    - scipy >=1.8
    - mumps-seq

tests:
  - python:
      imports:
        - mumps
  - requirements:
      run:
        - pip
        - pytest
    script:
      - pip check
      - "python -c \"import mumps; mumps.test()\""

about:
  summary: Bindings and Python interface for the MUMPS sparse solver
  license: BSD-2-Clause
  license_file: LICENSE
  homepage: https://gitlab.kwant-project.org/kwant/python-mumps

extra:
  recipe-maintainers:
    - akhmerov
